name: scheduled_deliveries
description: Process scheduled message deliveries and send them

schedule:
  quartz_cron_expression: "0 0 0 * * ?"  # Once per day at midnight UTC (configurable via WORKFLOW_SCHEDULE_CRON)
  timezone_id: "UTC"

tasks:
  - task_key: process_scheduled_deliveries
    description: Process scheduled message deliveries from queue
    notebook_task:
      notebook_path: /Workspace/Users/pravin.varma@databricks.com/cdp-demo/backend/scripts/workflows/scheduled_deliveries
      base_parameters:
        tenant_id: "demo_tenant"
    max_retries: 2
    timeout_seconds: 1800
    email_notifications:
      on_failure:
        - ${workflow.owner}

